export const siteConfig = {
  brand: {
    name: "SOUL",
    tagline: "The Essence of Timeless Elegance",
    description: "For over a century, SOUL has been synonymous with luxury and sophistication. Each bottle represents years of meticulous craftsmanship, combining rare ingredients sourced from the most prestigious regions worldwide.",
    founded: "1923",
    headquarters: "Paris, France",
    philosophy: "Crafted for Eternity",
  },
  
  navigation: [
    { name: "Home", href: "/" },
    { name: "Collection", href: "/products" },
    { name: "About", href: "/about" },
    { name: "Contact", href: "/contact" },
  ],

  products: [
    {
      id: "soul-eternite",
      name: "SOUL Éternité",
      image: "/soul1.png",
      description: "An everlasting signature — luminous notes of bergamot, jasmine, and amber create an aura of pure timelessness.",
      price: "$380",
      originalPrice: "$450",
      category: "Signature",
      size: "100ml",
      concentration: "Eau de Parfum",
      topNotes: ["Bergamot", "Pink Pepper", "Cardamom"],
      heartNotes: ["Jasmine", "Rose", "Lily of the Valley"],
      baseNotes: ["Amber", "Sandalwood", "Musk"],
      intensity: "Medium",
      longevity: "8-10 hours",
      sillage: "Moderate",
      season: ["Spring", "Summer"],
      occasion: ["Day", "Evening"],
      gender: "Unisex",
      inStock: true,
      featured: true,
      bestseller: true,
      limitedEdition: false,
      rating: 4.8,
      reviews: 1247,
    },
    {
      id: "soul-nocturne",
      name: "SOUL Nocturne",
      image: "/soul2.png",
      description: "Mysterious and intoxicating — midnight oud, dark rose, and smoked sandalwood envelop you in depth and allure.",
      price: "$420",
      originalPrice: "$500",
      category: "Luxury",
      size: "100ml",
      concentration: "Eau de Parfum",
      topNotes: ["Saffron", "Black Pepper", "Bergamot"],
      heartNotes: ["Dark Rose", "Oud", "Patchouli"],
      baseNotes: ["Sandalwood", "Amber", "Musk"],
      intensity: "Strong",
      longevity: "10-12 hours",
      sillage: "Strong",
      season: ["Autumn", "Winter"],
      occasion: ["Evening", "Night"],
      gender: "Unisex",
      inStock: true,
      featured: true,
      bestseller: false,
      limitedEdition: false,
      rating: 4.9,
      reviews: 892,
    },
    {
      id: "soul-lumina",
      name: "SOUL Lumina",
      image: "/soul3.png",
      description: "A radiant symphony — sparkling citrus, white florals, and golden musk illuminate your presence.",
      price: "$400",
      originalPrice: "$480",
      category: "Fresh",
      size: "100ml",
      concentration: "Eau de Parfum",
      topNotes: ["Lemon", "Grapefruit", "Orange Blossom"],
      heartNotes: ["White Florals", "Jasmine", "Magnolia"],
      baseNotes: ["Golden Musk", "Cedar", "Vanilla"],
      intensity: "Light-Medium",
      longevity: "6-8 hours",
      sillage: "Moderate",
      season: ["Spring", "Summer"],
      occasion: ["Day", "Evening"],
      gender: "Unisex",
      inStock: true,
      featured: true,
      bestseller: false,
      limitedEdition: false,
      rating: 4.7,
      reviews: 1034,
    },
    {
      id: "soul-mirage",
      name: "SOUL Mirage",
      image: "/soul4.png",
      description: "An ethereal illusion — soft peony, lychee, and musk veil the senses in delicate sophistication.",
      price: "$360",
      originalPrice: "$420",
      category: "Floral",
      size: "100ml",
      concentration: "Eau de Parfum",
      topNotes: ["Lychee", "Peach", "Green Leaves"],
      heartNotes: ["Peony", "Rose", "Magnolia"],
      baseNotes: ["White Musk", "Sandalwood", "Amber"],
      intensity: "Light",
      longevity: "6-8 hours",
      sillage: "Soft",
      season: ["Spring", "Summer"],
      occasion: ["Day", "Casual"],
      gender: "Feminine",
      inStock: true,
      featured: false,
      bestseller: false,
      limitedEdition: false,
      rating: 4.6,
      reviews: 756,
    },
    {
      id: "soul-obsidian",
      name: "SOUL Obsidian",
      image: "/soul5.png",
      description: "Commanding and powerful — rare oud, vetiver, and spiced amber forge a magnetic aura.",
      price: "$450",
      originalPrice: "$550",
      category: "Oriental",
      size: "100ml",
      concentration: "Eau de Parfum",
      topNotes: ["Black Pepper", "Cardamom", "Saffron"],
      heartNotes: ["Oud", "Rose", "Jasmine"],
      baseNotes: ["Vetiver", "Amber", "Sandalwood"],
      intensity: "Very Strong",
      longevity: "12+ hours",
      sillage: "Very Strong",
      season: ["Autumn", "Winter"],
      occasion: ["Evening", "Night", "Special"],
      gender: "Masculine",
      inStock: true,
      featured: false,
      bestseller: true,
      limitedEdition: true,
      rating: 4.9,
      reviews: 623,
    },
  ],

  categories: [
    { name: "All", value: "all" },
    { name: "Signature", value: "signature" },
    { name: "Luxury", value: "luxury" },
    { name: "Fresh", value: "fresh" },
    { name: "Floral", value: "floral" },
    { name: "Oriental", value: "oriental" },
  ],

  occasions: [
    { name: "Day", value: "day" },
    { name: "Evening", value: "evening" },
    { name: "Night", value: "night" },
    { name: "Casual", value: "casual" },
    { name: "Special", value: "special" },
  ],

  seasons: [
    { name: "Spring", value: "spring" },
    { name: "Summer", value: "summer" },
    { name: "Autumn", value: "autumn" },
    { name: "Winter", value: "winter" },
  ],

  social: {
    instagram: "https://instagram.com/soulparfum",
    facebook: "https://facebook.com/soulparfum",
    twitter: "https://twitter.com/soulparfum",
    pinterest: "https://pinterest.com/soulparfum",
  },

  contact: {
    email: "contact@soulparfum.com",
    phone: "+1 (555) 123-4567",
    address: "123 Champs-Élysées, 75008 Paris, France",
    hours: "Mon-Fri: 9AM-7PM, Sat-Sun: 10AM-6PM",
  },
};
  